/**
 * Per-build export — the **device-only** IO around the pure
 * `src/logic/export-txt.ts`. TXT writes the pure string to a cache file and
 * shares it; PDF renders an `expo-print` HTML→PDF (v1's `reportlab` doesn't exist
 * in RN) and shares that. Neither runs in the node test runner — the testable part
 * is the pure formatter; this is the wiring.
 */
import { File, Paths } from 'expo-file-system';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

import { type BuildSummaryData, formatExportDate, generateTextSummary } from '@/logic/export-txt';

/** A filesystem-safe base name derived from the build name. */
function safeBase(name: string): string {
  const slug = name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
  return slug || 'terrarium';
}

/** Write a string to a fresh cache file and return it. */
function writeCacheFile(fileName: string, contents: string): File {
  const file = new File(Paths.cache, fileName);
  if (file.exists) file.delete();
  file.create();
  file.write(contents);
  return file;
}

async function share(uri: string, mimeType: string, dialogTitle: string, UTI: string): Promise<void> {
  if (!(await Sharing.isAvailableAsync())) {
    throw new Error('Sharing isn’t available on this device.');
  }
  await Sharing.shareAsync(uri, { mimeType, dialogTitle, UTI });
}

/** Export a build as a plain-text summary and open the share sheet. */
export async function shareBuildTxt(data: BuildSummaryData): Promise<void> {
  const file = writeCacheFile(`${safeBase(data.name)}.txt`, generateTextSummary(data));
  await share(file.uri, 'text/plain', `Export “${data.name}”`, 'public.plain-text');
}

/** Export a build as a PDF (HTML→PDF via expo-print) and open the share sheet. */
export async function shareBuildPdf(data: BuildSummaryData): Promise<void> {
  const { uri } = await Print.printToFileAsync({ html: buildPdfHtml(data) });
  await share(uri, 'application/pdf', `Export “${data.name}”`, 'com.adobe.pdf');
}

// --- PDF HTML template -------------------------------------------------------

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * The PDF body — the same fields as the TXT summary, laid out as a clean document
 * (title rule, a label/value table, a plant list, a centered footer) that mirrors
 * v1's reportlab layout without the native dependency.
 */
function buildPdfHtml(data: BuildSummaryData): string {
  const rows: [string, string][] = [
    ['Container', data.containerName ?? 'Unknown Container'],
    ['Score', data.score !== null ? `${data.score}/100` : 'N/A'],
    ['Tags', data.tags.length > 0 ? data.tags.join(', ') : 'None'],
    ['Created', formatExportDate(data.createdAt)],
    ['Last Updated', formatExportDate(data.updatedAt)],
  ];
  const tableRows = rows
    .map(
      ([label, value]) =>
        `<tr><td class="label">${escapeHtml(label)}</td><td>${escapeHtml(value)}</td></tr>`,
    )
    .join('');
  const plantsList =
    data.plantNames.length > 0
      ? `<ul>${data.plantNames.map((p) => `<li>${escapeHtml(p)}</li>`).join('')}</ul>`
      : '<p class="muted">None</p>';

  return `<!DOCTYPE html><html><head><meta charset="utf-8" />
<style>
  * { font-family: -apple-system, Helvetica, Arial, sans-serif; color: #1f2a24; }
  body { margin: 48px; }
  h1 { font-size: 24px; margin: 0 0 12px; }
  hr { border: none; border-top: 1px solid #1f2a24; margin: 0 0 20px; }
  table { border-collapse: collapse; margin-bottom: 8px; }
  td { padding: 4px 24px 4px 0; font-size: 13px; vertical-align: top; }
  td.label { font-weight: 700; }
  h2 { font-size: 15px; margin: 24px 0 8px; }
  ul { margin: 0; padding-left: 18px; }
  li { font-size: 13px; margin-bottom: 4px; }
  .muted { color: #6b756e; font-size: 13px; }
  footer { margin-top: 48px; text-align: center; font-style: italic; font-size: 11px; color: #6b756e; }
</style></head>
<body>
  <h1>${escapeHtml(data.name)}</h1>
  <hr />
  <table>${tableRows}</table>
  <h2>Plants</h2>
  ${plantsList}
  <footer>Generated by Terrarium Planner</footer>
</body></html>`;
}
