import { describe, expect, it } from 'vitest';

import {
  type BuildSummaryData,
  formatExportDate,
  generateTextSummary,
  resolveBuildSummary,
} from '../export-txt';
import { makeContainerSpec, makePlant } from './factories';

const fittonia = makePlant({ slug: 'fittonia', commonName: 'Nerve Plant' });
const moss = makePlant({ slug: 'moss', commonName: 'Cushion Moss', closedTerrariumOk: true, openTerrariumOk: true });
const PLANTS = [fittonia, moss];
const sealedJar = makeContainerSpec({ slug: 'nano-sealed', name: 'Nano Sealed Jar', opening: 'sealed' });
const CONTAINERS = [sealedJar];

const SNAPSHOT = {
  containerShape: 'rectangular' as const,
  containerDimensions: { length: 15, width: 15, height: 20 },
  containerOpening: 'sealed' as const,
};

describe('formatExportDate', () => {
  it('formats a Date as YYYY-MM-DD', () => {
    expect(formatExportDate(new Date('2026-06-17T09:30:00Z'))).toMatch(/^\d{4}-\d{2}-\d{2}$/);
  });
  it('parses an ISO string', () => {
    expect(formatExportDate('2026-01-05T00:00:00.000Z')).toMatch(/^2026-01-05$/);
  });
  it('returns "Unknown" for null / undefined / empty / garbage (v1 parity)', () => {
    expect(formatExportDate(null)).toBe('Unknown');
    expect(formatExportDate(undefined)).toBe('Unknown');
    expect(formatExportDate('')).toBe('Unknown');
    expect(formatExportDate('not-a-date')).toBe('Unknown');
  });
});

describe('generateTextSummary — byte-faithful v1 layout', () => {
  const base: BuildSummaryData = {
    name: 'Mossy Jar',
    containerName: 'Nano Sealed Jar',
    score: 92,
    tags: ['beginner', 'sealed'],
    createdAt: '2026-01-05T00:00:00.000Z',
    updatedAt: '2026-02-10T00:00:00.000Z',
    plantNames: ['Nerve Plant', 'Cushion Moss'],
  };

  it('renders the header, label block, plant list and footer', () => {
    const txt = generateTextSummary(base);
    expect(txt).toContain('Terrarium Build: Mossy Jar');
    expect(txt).toContain('========================================');
    expect(txt).toContain('Container:    Nano Sealed Jar');
    expect(txt).toContain('Score:        92/100');
    expect(txt).toContain('Tags:         beginner, sealed');
    expect(txt).toContain('Created:      2026-01-05');
    expect(txt).toContain('Last Updated: 2026-02-10');
    expect(txt).toContain('- Nerve Plant');
    expect(txt).toContain('- Cushion Moss');
    expect(txt.trimEnd().endsWith('Generated by Terrarium Planner')).toBe(true);
  });

  it('falls back to N/A score, None tags, Unknown dates, and "- None" plants', () => {
    const txt = generateTextSummary({
      name: 'Empty',
      containerName: null,
      score: null,
      tags: [],
      plantNames: [],
    });
    expect(txt).toContain('Container:    Unknown Container');
    expect(txt).toContain('Score:        N/A');
    expect(txt).toContain('Tags:         None');
    expect(txt).toContain('Created:      Unknown');
    expect(txt).toContain('- None');
  });
});

describe('resolveBuildSummary — wires the engine honestly', () => {
  it('resolves container name, score, and plant common names', () => {
    const data = resolveBuildSummary(
      { name: 'Mossy Jar', plantSlugs: ['fittonia', 'moss'], tags: ['sealed'], ...SNAPSHOT },
      PLANTS,
      CONTAINERS,
    );
    expect(data.containerName).toBe('Custom Rectangular (4.5 L)');
    expect(data.score).not.toBeNull();
    expect(data.plantNames).toEqual(['Nerve Plant', 'Cushion Moss']);
  });

  it('exports score N/A (not a fabricated number) when scoring cannot run', () => {
    // No container snapshot and no slug → scoreBuild surfaces a diagnostic, score null.
    const data = resolveBuildSummary({ name: 'Broken', plantSlugs: ['fittonia'] }, PLANTS, CONTAINERS);
    expect(data.score).toBeNull();
    expect(generateTextSummary(data)).toContain('Score:        N/A');
  });

  it('falls back to the slug for an unknown plant rather than dropping it', () => {
    const data = resolveBuildSummary(
      { name: 'Mystery', plantSlugs: ['ghost-plant'], ...SNAPSHOT },
      PLANTS,
      CONTAINERS,
    );
    expect(data.plantNames).toEqual(['ghost-plant']);
  });
});
