/**
 * Per-build TXT export — a **pure string function** (port of v1
 * `engine/export.py::generate_text_summary`, the `reportlab`-free half). Kept in
 * `src/logic` so it imports nothing from `src/db`/`src/data` and is unit-tested in
 * the node runner; the device-side file-write + share lives in `src/lib/export.ts`.
 *
 * `resolveBuildSummary` shapes a saved build into the flat `BuildSummaryData` the
 * formatter (and the PDF HTML template) consume, using the same dependency-inverted
 * `scoreBuild` / `resolveBuildContainer` the screens use — seed `plants` /
 * `containers` are passed in, never imported, so engine purity holds.
 */
import type { Container } from '@/types/container';
import type { Plant } from '@/types/plant';

import { type BuildContainerSnapshot, resolveBuildContainer } from './containers';
import { scoreBuild } from './score-build';

/** The flat, presentation-ready shape both the TXT formatter and the PDF use. */
export interface BuildSummaryData {
  name: string;
  /** Resolved container name, or `null` when the build has no container. */
  containerName: string | null;
  /** 0–100, or `null` when scoring couldn't run (mirrors v1's `N/A`). */
  score: number | null;
  tags: string[];
  createdAt?: string | number | Date | null;
  updatedAt?: string | number | Date | null;
  plantNames: string[];
}

/** The minimal saved-build shape the summary resolver needs. */
export type SummarizableBuild = BuildContainerSnapshot & {
  name: string;
  plantSlugs: string[];
  tags?: string[];
  createdAt?: string | number | Date | null;
  updatedAt?: string | number | Date | null;
};

/**
 * Format a date as `YYYY-MM-DD`, or `"Unknown"` for a missing/unparseable value —
 * faithful to v1's `_format_date` (which returned "Unknown" on `None`/ValueError).
 */
export function formatExportDate(value: string | number | Date | null | undefined): string {
  if (value === null || value === undefined || value === '') return 'Unknown';
  const date = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(date.getTime())) return 'Unknown';
  // Format in UTC so an exported date is machine-timezone-independent (and matches
  // v1, which printed the tz-aware `Z` date without shifting it to local time).
  const yyyy = date.getUTCFullYear().toString().padStart(4, '0');
  const mm = (date.getUTCMonth() + 1).toString().padStart(2, '0');
  const dd = date.getUTCDate().toString().padStart(2, '0');
  return `${yyyy}-${mm}-${dd}`;
}

/**
 * Resolve a saved build (+ the seed catalogs) into `BuildSummaryData`. Container
 * name comes from `resolveBuildContainer`; the score from `scoreBuild` (so a
 * scoring failure exports honestly as `N/A`, not a fabricated number); plant names
 * from the seed catalog, falling back to the slug so nothing is silently dropped.
 */
export function resolveBuildSummary(
  build: SummarizableBuild,
  plants: readonly Plant[],
  containers: readonly Container[],
): BuildSummaryData {
  const container = resolveBuildContainer(build, containers);
  const scored = scoreBuild({ ...build, plantSlugs: build.plantSlugs }, plants, containers);
  const bySlug = new Map(plants.map((p) => [p.slug, p]));
  const plantNames = build.plantSlugs.map((slug) => bySlug.get(slug)?.commonName ?? slug);
  return {
    name: build.name,
    containerName: container?.name ?? null,
    score: scored.score,
    tags: build.tags ?? [],
    createdAt: build.createdAt,
    updatedAt: build.updatedAt,
    plantNames,
  };
}

/**
 * The plain-text build summary. Byte-for-byte the v1 layout (header rule, the
 * label/value block, the Plants list, the footer) so an exported file reads the
 * same on either app.
 */
export function generateTextSummary(data: BuildSummaryData): string {
  const containerName = data.containerName ?? 'Unknown Container';
  const scoreStr = data.score !== null ? `${data.score}/100` : 'N/A';
  const tagsStr = data.tags.length > 0 ? data.tags.join(', ') : 'None';
  const created = formatExportDate(data.createdAt);
  const updated = formatExportDate(data.updatedAt);
  const plantsBlock =
    data.plantNames.length > 0 ? data.plantNames.map((p) => `- ${p}`).join('\n') : '- None';

  return (
    `Terrarium Build: ${data.name}\n` +
    `========================================\n` +
    `Container:    ${containerName}\n` +
    `Score:        ${scoreStr}\n` +
    `Tags:         ${tagsStr}\n` +
    `Created:      ${created}\n` +
    `Last Updated: ${updated}\n` +
    `\n` +
    `Plants\n` +
    `-------\n` +
    `${plantsBlock}\n` +
    `\n` +
    `Generated by Terrarium Planner`
  );
}
